app = "kcd"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  NODE_ENV = "production"
  FLY = "true"
  PRIMARY_REGION = "den"

[mounts]
  source = "data"
  destination = "/data"

# IDEA: add back statics config here (fa0fbe9)

[experimental]
  enable_consul = true
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 200
    soft_limit = 150
    type = "requests"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
